name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      id: pytest
      run: |
        pytest

    - name: Notify Slack on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"SE ROMPIO TODO!!!"}' ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack on success
      if: success()
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"SE ARREGLO TODO!!!."}' ${{ secrets.SLACK_WEBHOOK_URL }}
  
  Sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GIT_TOKEN  }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN  }}
        with:
          args: >
              -Dsonar.organization=joaquingz89
              -Dsonar.projectKey=IdS-P2
              -Dsonar.python.coverage.reportPaths=cover



